name: Run Selenium Tests Exercise

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 18
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5

        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Run tests
        run: mvn clean test